name: bank_of_baku_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  # sizer: ^2.0.15
  responsive_sizer: ^3.1.1
  flutter_svg: ^1.1.4
  pin_code_fields: ^7.4.0
  badges: ^2.0.3
  dotted_border: ^2.0.0+2
  top_snackbar_flutter: ^2.1.1
  syncfusion_flutter_charts: ^20.2.49
  flutter_slidable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
#  flutter_native_splash: ^2.2.10+1
#
#flutter_native_splash:
#  background_image: assets/images/splash_logo.png
#  android: true
#  ios: false
#  # color: '#00A3C9'


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700